apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigning-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ntnxlab-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: "ntnxlab CA"
  secretName: ntnxlab-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigning-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ntnxlab-ca
spec:
  ca:
    secretName: ntnxlab-ca
