apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metallb
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          type: argo
  template:
    metadata:
      name: '{{name}}-metallb'
    spec:
      destination:
        namespace: metallb-system
        server: '{{server}}'
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
      source:
        chart: metallb
        helm:
          parameters:
          - name:  configInline
            value: |
                address-pools:
                - name: default
                  protocol: layer2
                  addresses:
                  - '{{metadata.annotations.ip-pool}}'
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 2.5.13
