apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metallb
  namespace: gitops
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          type: 'argo'
  template:
    metadata:
      name: '{{name}}-metallb'
    spec:
      destination:
        namespace: metallb-system
        server: '{{server}}'
      project: "infra"
      source:
        chart: metallb
        helm:
          parameters:
            address-pools:
            - name: default
              protocol: layer2
              addresses:
              - 172.23.131.87-172.23.131.89
        repoURL: https://metallb.github.io/metallb