apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          type: argo
  template:
    metadata:
      name: '{{name}}-ingress'
    spec:
      destination:
        namespace: ingress
        server: '{{server}}'
      project: "default"
      source:
        chart: nginx-ingress
        helm:
          parameters:
          - name:  service.type
            value: LoadBalancer
        repoURL: https://github.com/kubernetes/ingress-nginx/charts/ingress-nginx
        targetRevision: 4.0.13