apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          type: argo
  template:
    metadata:
      name: '{{name}}-ingress'
    spec:
      destination:
        namespace: ingress
        server: '{{server}}'
      project: "default"
      source:
        repoURL: https://kubernetes-charts.storage.googleapis.com/
        chart: nginx-ingress
        targetRevision: 1.40.3
        helm:
          parameters:
          - name:  service.type
            value: LoadBalancer