apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          type: argo
  template:
    metadata:
      name: '{{name}}-ingress'
    spec:
      destination:
        namespace: nginx-ingress
        server: '{{server}}'
      project: default
      source:
        chart: nginx-ingress
        helm:
          parameters:
          - name:  service.type
            value: LoadBalancer
        repoURL: kubernetes.github.io/ingress-nginx
        targetRevision: 4.0.13